# Generated by Django 4.2.6 on 2023-10-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('description', models.CharField(max_length=2000)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
